--- 
title: "R Module 1"
author: 
  - "Alex Fout^[Department of Statistics, Colorado State University, fout@colostate.edu]"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
description: This is the book for the R Intro Course at CSU.
documentclass: book
link-citations: yes
bibliography:
- src/book.bib
site: bookdown::bookdown_site
biblio-style: apalike
---


# Welcome!

```{r, knitr_options}
knitr::opts_chunk$set(fig.align="center")
```

Hi, and welcome to the R Module 1 course at Colorado State University!

This course is the first of three 1 credit courses intended to introduce the R programming language to those with little or no programming experience.

Through these Modules (courses), we'll explore how R can be used to do the following:

1. Perform basic computations and logic, just like any other programming language
1. Load, clean, analyze, and visualise data
1. Run scripts
1. Create reproducible reports so you can explain your work in a narrative form

In addition, you'll also be exposed to some aspects of the broader R community, including:

1. R as free, open source software
1. The RStudio free software
1. Publicly available packages which extend the capability of R
1. Events and community groups which advocate for the use of R and the support of R users

More detail will be provided in the Course Topics laid out in the next chapter.

## Associated CSU Course

This bookdown book is intended to accompany the associated course at Colorado State University, but the curriculum is free for anyone to access and use.
If you're reading the PDF or EPUB version of this book, you can find the "live" version at [https://csu-r.github.io/Module1/](https://csu-r.github.io/Module1/), and all of the source files for this book can be found at [https://github.com/CSU-R/Module1](https://github.com/CSU-R/Module1).

